server:
  port: 8090 # порт, по которому будет работать приложение
  shutdown: graceful # позволяет приложению завершать работу

logging:
  level:
    root: info

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0 # начальная версия базы данных
    locations: classpath:db/migration
    enabled: true # включает flyway
    default-schema: public
    schemas: public
    # Optional: custom name for the metadata table
    table: flyway_schema_history


  application:
    name: send-to-tax
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false # не показывать команды sql приложению
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect #  postgres
        format_sql: true # форматирует sql команды приложению
    open-in-view: false
